# Generated by Django 4.1.4 on 2023-01-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note_user'),
        ('main_app', '0002_note_user_photo'),
    ]

    operations = [
    ]
